GO

/****** Object:  Table [dbo].[TB_PEDIDO_PECA_LOG]    Script Date: 22/07/2021 14:51:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_PEDIDO_PECA_LOG](
	[ID_ITEM_PEDIDO_LOG] [numeric](9, 0) IDENTITY(1,1) NOT NULL,
	[ID_ITEM_PEDIDO] [numeric](9, 0) NULL,
	[DATA_RECEBIMENTO] [datetime] NULL,
	[QTD_PECA_RECEBIDA] [numeric](9, 0) NULL,
 CONSTRAINT [PK_TB_PEDIDO_PECA_LOG] PRIMARY KEY CLUSTERED 
(
	[ID_ITEM_PEDIDO_LOG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TB_PEDIDO_PECA_LOG]  WITH NOCHECK ADD  CONSTRAINT [FK_TB_PEDIDO_PECA_LOG_TB_PEDIDO_PECA] FOREIGN KEY([ID_ITEM_PEDIDO])
REFERENCES [dbo].[TB_PEDIDO_PECA] ([ID_ITEM_PEDIDO])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[TB_PEDIDO_PECA_LOG] CHECK CONSTRAINT [FK_TB_PEDIDO_PECA_LOG_TB_PEDIDO_PECA]
GO


