----- CAMPO TOOKEN tbVisitaPadrao -----

ALTER TABLE tbVisitaPadrao ADD TOKEN BIGINT NOT NULL


GO

CREATE NONCLUSTERED INDEX [IX_tbVisitaPadrao_TOKEN] ON [dbo].[tbVisitaPadrao]
(
	[TOKEN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


----- CAMPO TOOKEN tbOSPadrao -----

ALTER TABLE tbOSPadrao ADD TOKEN BIGINT NOT NULL


GO

CREATE NONCLUSTERED INDEX [IX_tbOSPadrao_TOKEN] ON [dbo].[tbOSPadrao]
(
	[TOKEN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


----- CAMPO TOOKEN tbPecaOS -----


ALTER TABLE tbPecaOS ADD TOKEN BIGINT NULL


GO

CREATE NONCLUSTERED INDEX [IX_tbPecaOS_TOKEN] ON [dbo].[tbPecaOS]
(
	[TOKEN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


----- CAMPO TOOKEN tbPendenciaOS -----


ALTER TABLE tbPendenciaOS ADD TOKEN BIGINT NULL


GO

CREATE NONCLUSTERED INDEX [IX_tbPendenciaOS_TOKEN] ON [dbo].[tbPendenciaOS]
(
	[TOKEN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



----- CAMPO TOOKEN TbRRRelatorioReclamacao -----

ALTER TABLE TbRRRelatorioReclamacao ADD TOKEN BIGINT NULL


GO

CREATE NONCLUSTERED INDEX [IX_TbRRRelatorioReclamacao_TOKEN] ON [dbo].[TbRRRelatorioReclamacao]
(
	[TOKEN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


----- CAMPO TOOKEN TB_PEDIDO -----


ALTER TABLE TB_PEDIDO ADD TOKEN BIGINT NULL

GO

CREATE NONCLUSTERED INDEX [IX_TB_PEDIDO_TOKEN] ON [dbo].[TB_PEDIDO]
(
	[TOKEN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


----- CAMPO TOOKEN TB_PEDIDO_PECA -----


ALTER TABLE TB_PEDIDO_PECA ADD TOKEN BIGINT NULL

GO

CREATE NONCLUSTERED INDEX [IX_TB_PEDIDO_PECA_TOKEN] ON [dbo].[TB_PEDIDO_PECA]
(
	[TOKEN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



----- AJUSTE FK TB_PEDIDO_PECA -----

GO

ALTER TABLE [dbo].[TB_PEDIDO_PECA] DROP CONSTRAINT [FK_TB_PEDIDO_PECA_TB_PEDIDO]
GO

ALTER TABLE [dbo].[TB_PEDIDO_PECA]  WITH NOCHECK ADD  CONSTRAINT [FK_TB_PEDIDO_PECA_TB_PEDIDO] FOREIGN KEY([ID_PEDIDO])
REFERENCES [dbo].[TB_PEDIDO] ([ID_PEDIDO])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[TB_PEDIDO_PECA] CHECK CONSTRAINT [FK_TB_PEDIDO_PECA_TB_PEDIDO]
GO


----- AJUSTE FK tbMensagem -----

GO

ALTER TABLE [dbo].[tbMensagem] DROP CONSTRAINT [FK_tbMensagem_TB_PEDIDO]
GO

ALTER TABLE [dbo].[tbMensagem]  WITH CHECK ADD  CONSTRAINT [FK_tbMensagem_TB_PEDIDO] FOREIGN KEY([ID_PEDIDO])
REFERENCES [dbo].[TB_PEDIDO] ([ID_PEDIDO])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[tbMensagem] CHECK CONSTRAINT [FK_tbMensagem_TB_PEDIDO]
GO
