


--ATENCAO--
--APOS RODAR ESSE SCRIPT, RODAR OBRIGATORIAMENTO O SCRIPT DE NOME Script_Indices_Manutencao




--TABELA: aux_ativo
CREATE NONCLUSTERED INDEX [IX_aux_ativo_CD_ATIVO_FIXO] ON [dbo].[aux_ativo]
(
	[CD_ATIVO_FIXO] ASC
)
INCLUDE([CD_MODELO]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE NONCLUSTERED INDEX [IX_aux_ativo_CD_MODELO] ON dbo.aux_ativo
(
	CD_MODELO ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

GO

CREATE NONCLUSTERED INDEX [IX_aux_ativo_DT_INVENTARIO] ON dbo.aux_ativo
(
	DT_INVENTARIO ASC
)
INCLUDE(CD_ATIVO_FIXO, CD_MODELO) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO


--TABELA: Aux_relato_ativo
CREATE NONCLUSTERED INDEX IX_Aux_relato_ativo_ID_RELATO ON dbo.Aux_relato_ativo
(
	ID_RELATO ASC
)
INCLUDE(CD_TECNICO, NR_DOCUMENTO, CD_CLIENTE, CD_ATIVO_FIXO) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX IX_Aux_relato_ativo_ID_RELATO_EQUIP ON dbo.Aux_relato_ativo
(
	ID_RELATO_EQUIP ASC
)
INCLUDE(NR_RELATORIO) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


--TABELA: DIM_TIME
ALTER TABLE [dbo].[DIM_TIME] ADD  CONSTRAINT [PK_DIM_TIME] PRIMARY KEY CLUSTERED 
(
	[COD_DIM_TIME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX IX_DIM_TIME_COD_DAY_YEA ON dbo.DIM_TIME
(
	COD_DAY_YEA ASC
)
INCLUDE(COD_DAY_QTR, DSC_DAY_QTR, COD_DAY_MTH, DSC_DAY_MTH) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


--TABELA: PECA_ATIVA
CREATE NONCLUSTERED INDEX IX_PECA_ATIVA_PECA ON dbo.PECA_ATIVA
(
	PECA ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


--TABELA: PlanilhaItens
CREATE NONCLUSTERED INDEX IX_planilha_Cliente ON dbo.planilha
(
	Cliente ASC
)
INCLUDE(Técnico1, Técnico2, Técnico3, Técnico4) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


--TABELA: PlanilhaItens
CREATE NONCLUSTERED INDEX IX_PlanilhaItens_cod ON dbo.PlanilhaItens
(
	cod ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


--TABELA: SIT_RAC_RAC
CREATE NONCLUSTERED INDEX IX_SIT_RAC_RAC_COD_SIT_RAC ON dbo.SIT_RAC_RAC
(
	COD_SIT_RAC ASC
)
INCLUDE(COD_SIT_SIC, DSC_SIT_RAC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_SIT_RAC_RAC_COD_SIT_SIC ON dbo.SIT_RAC_RAC
(
	COD_SIT_SIC ASC
)
INCLUDE(COD_SIT_RAC, DSC_SIT_RAC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


--TABELA: SIT_RAC_SIC_SIC
CREATE NONCLUSTERED INDEX IX_SIT_RAC_SIC_SIC_COD_SIT_SIC ON dbo.SIT_RAC_SIC_SIC
(
	COD_SIT_SIC ASC
)
INCLUDE(COD_SIT_SEG, DSC_SIT_SIC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_SIT_RAC_SIC_SIC_COD_SIT_SEG ON dbo.SIT_RAC_SIC_SIC
(
	COD_SIT_SEG ASC
)
INCLUDE(COD_SIT_SIC, DSC_SIT_SIC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


--TABELA: SIT_SEG_MAR_MARKET_INDUSTRY
CREATE NONCLUSTERED INDEX IX_SIT_SEG_MAR_MARKET_INDUSTRY_CD_MERCADO ON dbo.SIT_SEG_MAR_MARKET_INDUSTRY
(
	CD_MERCADO ASC
)
INCLUDE(DS_MERCADO) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: SIT_SIC_SEG_SEGMENT
CREATE NONCLUSTERED INDEX IX_SIT_SIC_SEG_SEGMENT_CD_MERCADO ON dbo.SIT_SIC_SEG_SEGMENT
(
	CD_MERCADO ASC
)
INCLUDE(CD_SEGMENTO, DS_SEGMENTO) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

--TABELA: T_QTD_TECNICOS
CREATE NONCLUSTERED INDEX IX_T_QTD_TECNICOS_CD_CLIENTE ON dbo.T_QTD_TECNICOS
(
	CD_CLIENTE ASC
)
INCLUDE(QtdTecnicos) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


--TABELA: T_RCM
CREATE NONCLUSTERED INDEX IX_T_RCM_CCUST ON dbo.T_RCM
(
	CCUST ASC
)
INCLUDE(CAD1, CAD2, CAD3, CPHON, CNME, CSTE, CZIP) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: T_RDVM
CREATE NONCLUSTERED INDEX IX_T_RDVM_RVCUST ON dbo.T_RDVM
(
	RVCUST ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: T_TECNICOS_ORDEM
CREATE NONCLUSTERED INDEX IX_T_TECNICOS_ORDEM_CD_CLIENTE ON dbo.T_TECNICOS_ORDEM
(
	CD_CLIENTE ASC
)
INCLUDE(CD_TECNICO, CD_ORDEM) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


--TABELA: TB_ATIVO_FIXO
CREATE NONCLUSTERED INDEX IX_TB_ATIVO_FIXO_CD_STATUS_ATIVO ON dbo.TB_ATIVO_FIXO
(
	CD_STATUS_ATIVO ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_TB_ATIVO_FIXO_CD_SITUACAO_ATIVO ON dbo.TB_ATIVO_FIXO
(
	CD_SITUACAO_ATIVO ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_TB_ATIVO_FIXO_CD_LINHA_PRODUTO ON dbo.TB_ATIVO_FIXO
(
	CD_LINHA_PRODUTO ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: TB_CLIENTE
CREATE NONCLUSTERED INDEX IX_TB_CLIENTE_CD_VENDEDOR ON dbo.TB_CLIENTE
(
	CD_VENDEDOR ASC
)
INCLUDE(CD_CLIENTE, NM_CLIENTE) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_TB_CLIENTE_CD_EXECUTIVO ON dbo.TB_CLIENTE
(
	CD_EXECUTIVO ASC
)
INCLUDE(CD_CLIENTE, NM_CLIENTE, CD_VENDEDOR) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_TB_CLIENTE_ID_SEGMENTO ON dbo.TB_CLIENTE
(
	ID_SEGMENTO ASC
)
INCLUDE(CD_CLIENTE, NM_CLIENTE, CD_VENDEDOR) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


--TABELA: TB_CLIENTE_RL_CURTO
CREATE NONCLUSTERED INDEX IX_TB_CLIENTE_RL_CURTO_CD_CLIENTE ON dbo.TB_CLIENTE_RL_CURTO
(
	CD_CLIENTE ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


--TABELA: TB_CONSUMIVEL
CREATE NONCLUSTERED INDEX IX_TB_CONSUMIVEL_CD_LINHA_PRODUTO ON dbo.TB_CONSUMIVEL
(
	CD_LINHA_PRODUTO ASC
)
INCLUDE(CD_CONSUMIVEL, DS_CONSUMIVEL) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_TB_CONSUMIVEL_CD_COMMODITY ON dbo.TB_CONSUMIVEL
(
	CD_COMMODITY ASC
)
INCLUDE(CD_CONSUMIVEL, DS_CONSUMIVEL, DS_COMMODITY) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX IX_TB_CONSUMIVEL_CD_MAJOR ON dbo.TB_CONSUMIVEL
(
	CD_MAJOR ASC
)
INCLUDE(CD_CONSUMIVEL, DS_CONSUMIVEL, DS_MAJOR) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX IX_TB_CONSUMIVEL_CD_FAMILY ON dbo.TB_CONSUMIVEL
(
	CD_FAMILY ASC
)
INCLUDE(CD_CONSUMIVEL, DS_CONSUMIVEL, DS_FAMILY) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX IX_TB_CONSUMIVEL_CD_SUB_FAMILY ON dbo.TB_CONSUMIVEL
(
	CD_SUB_FAMILY ASC
)
INCLUDE(CD_CONSUMIVEL, DS_CONSUMIVEL, DS_SUB_FAMILY) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


--TABELA: TB_CONSUMIVEL
CREATE NONCLUSTERED INDEX IX_TB_CONSUMIVEL_CARGA_CD_CONSUMIVEL ON dbo.TB_CONSUMIVEL_CARGA
(
	CD_CONSUMIVEL ASC
)
INCLUDE(CD_LINHA_PRODUTO) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


--TABELA: TB_CONSUMIVEL_CARGA
CREATE NONCLUSTERED INDEX IX_TB_CONSUMIVEL_CARGA_CD_CONSUMIVEL ON dbo.TB_CONSUMIVEL_CARGA
(
	CD_CONSUMIVEL ASC
)
INCLUDE(CD_LINHA_PRODUTO) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


--TABELA: TB_CONTRATO
CREATE NONCLUSTERED INDEX IX_TB_CONTRATO_CD_CLIENTE ON dbo.TB_CONTRATO
(
	CD_CLIENTE ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX IX_TB_CONTRATO_CD_STATUS_CONTRATO ON dbo.TB_CONTRATO
(
	CD_STATUS_CONTRATO ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: TB_DEPTO
CREATE NONCLUSTERED INDEX IX_TB_DEPTO_COD_DPT ON dbo.TB_DEPTO
(
	COD_DPT ASC
)
INCLUDE(DSC_DPT) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


--TABELA: TB_MODELO
CREATE NONCLUSTERED INDEX IX_TB_MODELO_CD_GRUPO_MODELO ON dbo.TB_MODELO
(
	CD_GRUPO_MODELO ASC
)
INCLUDE(CD_MODELO, DS_MODELO) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_TB_MODELO_ID_CATEGORIA ON dbo.TB_MODELO
(
	ID_CATEGORIA ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: TB_PECA
CREATE NONCLUSTERED INDEX IX_TB_PECA_FL_ATIVO_PECA ON dbo.TB_PECA
(
	FL_ATIVO_PECA ASC
)
INCLUDE(CD_PECA, DS_PECA) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: TB_PEDIDO
CREATE NONCLUSTERED INDEX IX_TB_PEDIDO_CD_TECNICO ON dbo.TB_PEDIDO
(
	CD_TECNICO ASC
)
INCLUDE(ID_PEDIDO, CD_PEDIDO, TP_TIPO_PEDIDO, CD_CLIENTE) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX IX_TB_PEDIDO_DT_CRIACAO ON dbo.TB_PEDIDO
(
	DT_CRIACAO ASC
)
INCLUDE(ID_PEDIDO, CD_PEDIDO, CD_TECNICO, TP_TIPO_PEDIDO, CD_CLIENTE) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX IX_TB_PEDIDO_ID_STATUS_PEDIDO ON dbo.TB_PEDIDO
(
	ID_STATUS_PEDIDO ASC
)
INCLUDE(ID_PEDIDO, CD_PEDIDO, CD_TECNICO, TP_TIPO_PEDIDO, CD_CLIENTE) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX IX_TB_PEDIDO_TP_TIPO_PEDIDO ON dbo.TB_PEDIDO
(
	TP_TIPO_PEDIDO ASC
)
INCLUDE(ID_PEDIDO, CD_PEDIDO, CD_TECNICO, CD_CLIENTE) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_TB_PEDIDO_CD_CLIENTE ON dbo.TB_PEDIDO
(
	CD_CLIENTE ASC
)
INCLUDE(ID_PEDIDO, CD_PEDIDO, CD_TECNICO, TP_TIPO_PEDIDO) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX IX_TB_PEDIDO_CD_PEDIDO ON dbo.TB_PEDIDO
(
	CD_PEDIDO ASC
)
INCLUDE(ID_PEDIDO, CD_CLIENTE, CD_TECNICO, TP_TIPO_PEDIDO) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


--TABELA: TB_PEDIDO_PECA
CREATE NONCLUSTERED INDEX IX_TB_PEDIDO_PECA_CD_PECA ON dbo.TB_PEDIDO_PECA
(
	CD_PECA ASC
)
INCLUDE(ID_PEDIDO, ID_ITEM_PEDIDO, ID_LOTE_APROVACAO, QTD_SOLICITADA, QTD_APROVADA, QTD_RECEBIDA, QTD_APROVADA_3M1, QTD_APROVADA_3M2, QTD_ULTIMO_RECEBIMENTO) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_TB_PEDIDO_PECA_ID_LOTE_APROVACAO ON dbo.TB_PEDIDO_PECA
(
	ID_LOTE_APROVACAO ASC
)
INCLUDE(ID_PEDIDO, ID_ITEM_PEDIDO, CD_PECA, QTD_SOLICITADA, QTD_APROVADA, QTD_RECEBIDA, QTD_APROVADA_3M1, QTD_APROVADA_3M2, QTD_ULTIMO_RECEBIMENTO) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


--TABELA: TB_PEDIDO_PECA_LOG
CREATE NONCLUSTERED INDEX IX_TB_PEDIDO_PECA_LOG_ID_ITEM_PEDIDO ON dbo.TB_PEDIDO_PECA_LOG
(
	ID_ITEM_PEDIDO ASC
)
INCLUDE(DATA_RECEBIMENTO, QTD_PECA_RECEBIDA) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: TB_RELATO
ALTER TABLE dbo.TB_RELATO ADD  CONSTRAINT PK_TB_RELATO PRIMARY KEY CLUSTERED 
(
	ID_RELATO ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



--TABELA: TB_RELATO_EQUIP_PECA
ALTER TABLE dbo.TB_RELATO_EQUIP_PECA ADD  CONSTRAINT PK_TB_RELATO_EQUIP_PECA PRIMARY KEY CLUSTERED 
(
	ID_RELATO_PECA ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX IX_TB_RELATO_EQUIP_PECA_CD_PECA ON dbo.TB_RELATO_EQUIP_PECA
(
	CD_PECA ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: TB_RESUMO_CONSUMIVEL

CREATE NONCLUSTERED INDEX IX_TB_RESUMO_CONSUMIVEL_CD_MES ON dbo.TB_RESUMO_CONSUMIVEL
(
	CD_MES ASC
)
INCLUDE(CD_CONSUMIVEL, QT_VENDAS, QT_VENDAS_CV, PR_PRATICADO, PR_PRATICADO_CV) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: TB_TECNICO

CREATE NONCLUSTERED INDEX IX_TB_TECNICO_ID_USUARIO_COORDENADOR ON dbo.TB_TECNICO
(
	ID_USUARIO_COORDENADOR ASC
)
INCLUDE(CD_TECNICO, NM_TECNICO) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_TB_TECNICO_ID_USUARIO ON dbo.TB_TECNICO
(
	ID_USUARIO ASC
)
INCLUDE(CD_TECNICO, NM_TECNICO) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX IX_TB_TECNICO_CD_EMPRESA ON dbo.TB_TECNICO
(
	CD_EMPRESA ASC
)
INCLUDE(CD_TECNICO, NM_TECNICO) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_TB_TECNICO_NM_TECNICO ON dbo.TB_TECNICO
(
	NM_TECNICO ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: TB_TMP_RESULTADO_PL

CREATE NONCLUSTERED INDEX IX_TB_TMP_RESULTADO_PL_CD_LINHA ON dbo.TB_TMP_RESULTADO_PL
(
	CD_LINHA ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_TB_TMP_RESULTADO_PL_CD_COMPETENCIA ON dbo.TB_TMP_RESULTADO_PL
(
	CD_COMPETENCIA ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_TB_TMP_RESULTADO_PL_CD_DIVISAO ON dbo.TB_TMP_RESULTADO_PL
(
	CD_DIVISAO ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX IX_TB_TMP_RESULTADO_PL_CD_MAJOR ON dbo.TB_TMP_RESULTADO_PL
(
	CD_MAJOR ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: TB_TRANSF_PECAS

CREATE NONCLUSTERED INDEX IX_TB_TRANSF_PECAS_CD_USUARIO ON dbo.TB_TRANSF_PECAS
(
	CD_USUARIO ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: TB_VENDAS_CLIENTE_MAJOR

CREATE NONCLUSTERED INDEX IX_TB_VENDAS_CLIENTE_MAJOR_CD_CLIENTE ON dbo.TB_VENDAS_CLIENTE_MAJOR
(
	CD_CLIENTE ASC
)
INCLUDE(CD_CONSUMIVEL, CD_MES, QT_VENDAS, PR_PRATICADO, PR_PRATICADO_CV, QT_VENDAS_CV, COD_DIM_DPT_SSTR, COD_PRD_MJR) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_TB_VENDAS_CLIENTE_MAJOR_CD_CONSUMIVEL ON dbo.TB_VENDAS_CLIENTE_MAJOR
(
	CD_CONSUMIVEL ASC
)
INCLUDE(CD_CLIENTE, CD_MES, QT_VENDAS, PR_PRATICADO, PR_PRATICADO_CV, QT_VENDAS_CV, COD_DIM_DPT_SSTR, COD_PRD_MJR) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: TB_VENDAS_CLIENTE_RL_CURTO

CREATE NONCLUSTERED INDEX IX_TB_VENDAS_CLIENTE_MAJOR_CD_CLIENTE ON dbo.TB_VENDAS_CLIENTE_RL_CURTO
(
	CD_CLIENTE ASC
)
INCLUDE(COD_DIM_DPT_SSTR, CD_CONSUMIVEL, CD_MES, QT_VENDAS, QT_VENDAS_CV, PR_PRATICADO, PR_PRATICADO_CV) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_TB_VENDAS_CLIENTE_MAJOR_CD_CONSUMIVEL ON dbo.TB_VENDAS_CLIENTE_RL_CURTO
(
	CD_CONSUMIVEL ASC
)
INCLUDE(COD_DIM_DPT_SSTR, CD_CLIENTE, CD_MES, QT_VENDAS, QT_VENDAS_CV, PR_PRATICADO, PR_PRATICADO_CV) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX IX_TB_VENDAS_CLIENTE_MAJOR_COD_DIM_DPT_SSTR ON dbo.TB_VENDAS_CLIENTE_RL_CURTO
(
	COD_DIM_DPT_SSTR ASC
)
INCLUDE(CD_CONSUMIVEL, CD_CLIENTE, CD_MES, QT_VENDAS, QT_VENDAS_CV, PR_PRATICADO, PR_PRATICADO_CV) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: TB_VENDEDOR

CREATE NONCLUSTERED INDEX IX_TB_VENDEDOR_ID_USUARIO ON dbo.TB_VENDEDOR
(
	ID_USUARIO ASC
)
INCLUDE(CD_VENDEDOR, NM_VENDEDOR, FL_ATIVO) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX IX_TB_VENDEDOR_ID_USUARIO_REGIONAL ON dbo.TB_VENDEDOR
(
	ID_USUARIO_REGIONAL ASC
)
INCLUDE(CD_VENDEDOR, NM_VENDEDOR, FL_ATIVO) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_TB_VENDEDOR_FL_ATIVO ON dbo.TB_VENDEDOR
(
	FL_ATIVO ASC
)
INCLUDE(CD_VENDEDOR, NM_VENDEDOR) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: tbAnexo

CREATE NONCLUSTERED INDEX IX_tbAnexo_ID_WF_PEDIDO_EQUIP ON dbo.tbAnexo
(
	ID_WF_PEDIDO_EQUIP ASC
)
INCLUDE(cdsTituloAnexo, cdsResponsavel, cdsNomeArquivo, cdsDescricaoAnexo, ncdOrdem) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: tbContato

CREATE NONCLUSTERED INDEX IX_TB_tbContato_nidTipoContato ON dbo.tbContato
(
	nidTipoContato ASC
)
INCLUDE(nidContato, cnmContato) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX IX_TB_tbContato_nidEmpresa ON dbo.tbContato
(
	nidEmpresa ASC
)
INCLUDE(nidContato, cnmContato) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_TB_tbContato_cnmContato ON dbo.tbContato
(
	cnmContato ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: tbEstoque

CREATE NONCLUSTERED INDEX IX_tbEstoque_CD_TECNICO ON dbo.tbEstoque
(
	CD_TECNICO ASC
)
INCLUDE(CD_ESTOQUE, DS_ESTOQUE, TP_ESTOQUE_TEC_3M) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbEstoque_DS_ESTOQUE ON dbo.tbEstoque
(
	DS_ESTOQUE ASC
)
INCLUDE(CD_ESTOQUE, TP_ESTOQUE_TEC_3M, FL_ATIVO) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX IX_tbEstoque_ID_USU_RESPONSAVEL ON dbo.tbEstoque
(
	ID_USU_RESPONSAVEL ASC
)
INCLUDE(CD_ESTOQUE, DS_ESTOQUE, TP_ESTOQUE_TEC_3M, FL_ATIVO) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbEstoque_TP_ESTOQUE_TEC_3M ON dbo.tbEstoque
(
	TP_ESTOQUE_TEC_3M ASC
)
INCLUDE(CD_ESTOQUE, DS_ESTOQUE, FL_ATIVO) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: tbEstoqueMovi

CREATE NONCLUSTERED INDEX IX_tbEstoqueMovi_CD_TP_MOVIMENTACAO ON dbo.tbEstoqueMovi
(
	CD_TP_MOVIMENTACAO ASC
)
INCLUDE(ID_OS, CD_PECA, TP_ENTRADA_SAIDA, CD_CLIENTE) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX IX_tbEstoqueMovi_ID_OS ON dbo.tbEstoqueMovi
(
	ID_OS ASC
)
INCLUDE(CD_TP_MOVIMENTACAO, CD_PECA, TP_ENTRADA_SAIDA, CD_CLIENTE, QT_PECA) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX IX_tbEstoqueMovi_ID_ESTOQUE ON dbo.tbEstoqueMovi
(
	ID_ESTOQUE ASC
)
INCLUDE(CD_TP_MOVIMENTACAO, CD_PECA, TP_ENTRADA_SAIDA, CD_CLIENTE, QT_PECA) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbEstoqueMovi_CD_PECA ON dbo.tbEstoqueMovi
(
	CD_PECA ASC
)
INCLUDE(CD_TP_MOVIMENTACAO, TP_ENTRADA_SAIDA, CD_CLIENTE, QT_PECA) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX IX_tbEstoqueMovi_ID_USU_MOVI ON dbo.tbEstoqueMovi
(
	ID_USU_MOVI ASC
)
INCLUDE(CD_TP_MOVIMENTACAO, TP_ENTRADA_SAIDA, CD_CLIENTE, QT_PECA) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX IX_tbEstoqueMovi_CD_CLIENTE ON dbo.tbEstoqueMovi
(
	CD_CLIENTE ASC
)
INCLUDE(CD_TP_MOVIMENTACAO, TP_ENTRADA_SAIDA, QT_PECA) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbEstoqueMovi_DT_MOVIMENTACAO ON dbo.tbEstoqueMovi
(
	DT_MOVIMENTACAO ASC
)
INCLUDE(ID_OS, CD_PECA, TP_ENTRADA_SAIDA, CD_CLIENTE) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


--TABELA: tbEstoquePeca

CREATE NONCLUSTERED INDEX IX_tbEstoquePeca_CD_PECA ON dbo.tbEstoquePeca
(
	CD_PECA ASC
)
INCLUDE(QT_PECA_ATUAL) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX IX_tbEstoquePeca_ID_ESTOQUE ON dbo.tbEstoquePeca
(
	ID_ESTOQUE ASC
)
INCLUDE(CD_PECA, QT_PECA_ATUAL) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX IX_tbEstoquePeca_DT_ULT_MOVIM ON dbo.tbEstoquePeca
(
	DT_ULT_MOVIM ASC
)
INCLUDE(ID_ESTOQUE, CD_PECA, QT_PECA_ATUAL) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: tbFuncao
CREATE NONCLUSTERED INDEX IX_tbFuncao_ccdFuncao ON dbo.tbFuncao
(
	ccdFuncao ASC
)
INCLUDE(cdsFuncao, bidAtivo) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: tbLog
CREATE NONCLUSTERED INDEX IX_tbFuncao_nidPK ON dbo.tbLog
(
	nidPK ASC
)
INCLUDE(cnmTabela, ccdAcao) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX IX_tbFuncao_cnmTabela ON dbo.tbLog
(
	cnmTabela ASC
)
INCLUDE(nidPK, ccdAcao) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: tbLogErro
ALTER TABLE dbo.tbLogErro ADD  CONSTRAINT PK_tbLogErro PRIMARY KEY CLUSTERED 
(
	nidLogErro ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE NONCLUSTERED INDEX IX_tbLogErro_DataHoraErro ON dbo.tbLogErro
(
	DataHoraErro ASC
)
INCLUDE(Servidor, Sistema, Origem, Usuario, Classe, Metodo, StackTrace) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbLogErro_Sistema ON dbo.tbLogErro
(
	Sistema ASC
)
INCLUDE(Servidor, Origem, Usuario, Classe, Metodo, StackTrace) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: tbLogSincronismo
ALTER TABLE dbo.tbLogSincronismo ADD  CONSTRAINT PK_tbLogSincronismo PRIMARY KEY CLUSTERED 
(
	id_log_sincronismo ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



--TABELA: tbLogStatusOS
CREATE NONCLUSTERED INDEX IX_tbLogStatusOS_ID_OS ON dbo.tbLogStatusOS
(
	ID_OS ASC
)
INCLUDE(DT_DATA_LOG_OS, ST_TP_STATUS_VISITA_OS, nidUsuarioAtualizacao) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO




--TABELA: tbLogStatusOS
CREATE NONCLUSTERED INDEX IX_tbLogStatusOSPadrao_ID_OS ON dbo.tbLogStatusOSPadrao
(
	ID_OS ASC
)
INCLUDE(DT_DATA_LOG_OS, ST_STATUS_OS, nidUsuarioAtualizacao) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: tbLogStatusVisita
CREATE NONCLUSTERED INDEX IX_tbLogStatusVisita_ID_VISITA ON dbo.tbLogStatusVisita
(
	ID_VISITA ASC
)
INCLUDE(DT_DATA_LOG_VISITA, ST_TP_STATUS_VISITA_OS, nidUsuarioAtualizacao) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: tbLogStatusVisitaPadrao
CREATE NONCLUSTERED INDEX IX_tbLogStatusVisitaPadrao_ID_VISITA ON dbo.tbLogStatusVisitaPadrao
(
	ID_VISITA ASC
)
INCLUDE(DT_DATA_LOG_VISITA, ST_STATUS_VISITA, nidUsuarioAtualizacao) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


--TABELA: tbLoteAprovacao
CREATE NONCLUSTERED INDEX IX_tbLoteAprovacao_ID_USUARIO ON dbo.tbLoteAprovacao
(
	ID_USUARIO ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: tbMensagem
CREATE NONCLUSTERED INDEX IX_tbMensagem_ID_PEDIDO ON dbo.tbMensagem
(
	ID_PEDIDO ASC
)
INCLUDE(DT_OCORRENCIA, DS_MENSAGEM) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX IX_tbMensagem_ID_USUARIO ON dbo.tbMensagem
(
	ID_USUARIO ASC
)
INCLUDE(DT_OCORRENCIA, DS_MENSAGEM) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


--TABELA: tbNotificacao
CREATE NONCLUSTERED INDEX IX_tbNotificacao_ID_USUARIO ON dbo.tbNotificacao
(
	ID_USUARIO ASC
)
INCLUDE(TITULO, MENSAGEM, LIDA, DATA_INCLUSAO) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO




--TABELA: tbOSPadrao
CREATE NONCLUSTERED INDEX IX_tbOSPadrao_DT_DATA_OS ON dbo.tbOSPadrao
(
	DT_DATA_OS ASC
)
INCLUDE(ST_STATUS_OS, CD_TIPO_OS, CD_TECNICO, CD_CLIENTE) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbOSPadrao_ST_STATUS_OS ON dbo.tbOSPadrao
(
	ST_STATUS_OS ASC
)
INCLUDE(DT_DATA_OS, CD_TIPO_OS, CD_TECNICO, CD_CLIENTE) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbOSPadrao_CD_CLIENTE ON dbo.tbOSPadrao
(
	CD_CLIENTE ASC
)
INCLUDE(DT_DATA_OS, CD_TIPO_OS, CD_TECNICO) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX IX_tbOSPadrao_CD_TECNICO ON dbo.tbOSPadrao
(
	CD_TECNICO ASC
)
INCLUDE(DT_DATA_OS, CD_TIPO_OS, CD_CLIENTE) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX IX_tbOSPadrao_CD_ATIVO_FIXO ON dbo.tbOSPadrao
(
	CD_ATIVO_FIXO ASC
)
INCLUDE(DT_DATA_OS, CD_TIPO_OS, CD_TECNICO, CD_CLIENTE) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbOSPadrao_CD_TIPO_OS ON dbo.tbOSPadrao
(
	CD_TIPO_OS ASC
)
INCLUDE(DT_DATA_OS, CD_TECNICO, CD_CLIENTE) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO




--TABELA: tbParametro
CREATE NONCLUSTERED INDEX IX_tbParametro_ccdParametro ON dbo.tbParametro
(
	ccdParametro ASC
)
INCLUDE(cdsParametro) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: tbPecaRecuperada
ALTER TABLE dbo.tbPecaRecuperada ADD  CONSTRAINT PK_tbPecaRecuperada PRIMARY KEY CLUSTERED 
(
	ID_PECA_RECUPERADA ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE NONCLUSTERED INDEX IX_tbPecaRecuperada_CD_PECA ON dbo.tbPecaRecuperada
(
	CD_PECA ASC
)
INCLUDE(CD_PECA_RECUPERADA) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


--TABELA: tbPendenciaOS
CREATE NONCLUSTERED INDEX IX_tbPendenciaOS_ID_OS ON dbo.tbPendenciaOS
(
	ID_OS ASC
)
INCLUDE(DT_ABERTURA, DS_DESCRICAO, CD_PECA, CD_TECNICO) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX IX_tbPendenciaOS_CD_PECA ON dbo.tbPendenciaOS
(
	CD_PECA ASC
)
INCLUDE(ID_OS, DT_ABERTURA, DS_DESCRICAO, CD_TECNICO) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX IX_tbPendenciaOS_CD_TECNICO ON dbo.tbPendenciaOS
(
	CD_TECNICO ASC
)
INCLUDE(ID_OS, DT_ABERTURA, DS_DESCRICAO, CD_PECA) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: tbPerfil
CREATE NONCLUSTERED INDEX IX_tbPerfil_cdsPerfil ON dbo.tbPerfil
(
	cdsPerfil ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: tbPerfilFuncao
CREATE NONCLUSTERED INDEX IX_tbPerfilFuncao_nidPerfil ON dbo.tbPerfilFuncao
(
	nidPerfil ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbPerfilFuncao_nidFuncao ON dbo.tbPerfilFuncao
(
	nidFuncao ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: tbPlanoZero
CREATE NONCLUSTERED INDEX IX_tbPlanoZero_CD_PECA ON dbo.tbPlanoZero
(
	CD_PECA ASC
)
INCLUDE(CD_MODELO, CD_GRUPO_MODELO, CD_CRITICIDADE_ABC, ID_USU_RESPONSAVEL, DT_CRIACAO) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbPlanoZero_CD_MODELO ON dbo.tbPlanoZero
(
	CD_MODELO ASC
)
INCLUDE(CD_PECA, CD_GRUPO_MODELO, CD_CRITICIDADE_ABC, ID_USU_RESPONSAVEL, DT_CRIACAO) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbPlanoZero_CD_CRITICIDADE_ABC ON dbo.tbPlanoZero
(
	CD_CRITICIDADE_ABC ASC
)
INCLUDE(CD_MODELO, CD_PECA, CD_GRUPO_MODELO, ID_USU_RESPONSAVEL, DT_CRIACAO) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX IX_tbPlanoZero_ID_USU_RESPONSAVEL ON dbo.tbPlanoZero
(
	ID_USU_RESPONSAVEL ASC
)
INCLUDE(CD_MODELO, CD_PECA, CD_GRUPO_MODELO, DT_CRIACAO, CD_CRITICIDADE_ABC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


--TABELA: tbRelatorioKAT
CREATE NONCLUSTERED INDEX IX_tbRelatorioKAT_ ON dbo.tbRelatorioKAT
(
	CD_CLIENTE ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: tbRRComent
CREATE NONCLUSTERED INDEX IX_tbRRComent_ID_RELATORIO_RECLAMACAO ON dbo.tbRRComent
(
	ID_RELATORIO_RECLAMACAO ASC
)
INCLUDE(DS_COMENT) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: tbRRRelatorioReclamacao
CREATE NONCLUSTERED INDEX IX_tbRRRelatorioReclamacao_CD_TECNICO ON dbo.tbRRRelatorioReclamacao
(
	CD_TECNICO ASC
)
INCLUDE(ID_OS, CD_PECA) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbRRRelatorioReclamacao_CD_CLIENTE ON dbo.tbRRRelatorioReclamacao
(
	CD_CLIENTE ASC
)
INCLUDE(ID_OS, CD_PECA) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbRRRelatorioReclamacao_CD_ATIVO_FIXO ON dbo.tbRRRelatorioReclamacao
(
	CD_ATIVO_FIXO ASC
)
INCLUDE(ID_OS, CD_PECA) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbRRRelatorioReclamacao_CD_PECA ON dbo.tbRRRelatorioReclamacao
(
	CD_PECA ASC
)
INCLUDE(ID_OS) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbRRRelatorioReclamacao_CD_GRUPO_RESPONS ON dbo.tbRRRelatorioReclamacao
(
	CD_GRUPO_RESPONS ASC
)
INCLUDE(ID_OS, CD_PECA) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbRRRelatorioReclamacao_ID_OS ON dbo.tbRRRelatorioReclamacao
(
	ID_OS ASC
)
INCLUDE(CD_PECA, CD_CLIENTE, CD_ATIVO_FIXO, DS_MOTIVO, DS_DESCRICAO) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: tbRRStatus
CREATE NONCLUSTERED INDEX IX_tbRRStatus_ST_STATUS_RR ON dbo.tbRRStatus
(
	ST_STATUS_RR ASC
)
INCLUDE(DS_STATUS_NOME, DS_STATUS_NOME_REDUZ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO




--TABELA: tbSatisfPesquisa
ALTER TABLE dbo.tbSatisfPesquisa ADD  CONSTRAINT PK_tbSatisfPesquisa PRIMARY KEY CLUSTERED 
(
	ID_PESQUISA_SATISF ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX IX_tbSatisfPesquisa_DS_TITULO ON dbo.tbSatisfPesquisa
(
	DS_TITULO ASC
)
INCLUDE(DT_CRIACAO, ST_STATUS_PESQUISA, DS_DESCRICAO) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbSatisfPesquisa_DT_CRIACAO ON dbo.tbSatisfPesquisa
(
	DT_CRIACAO ASC
)
INCLUDE(DS_TITULO, ST_STATUS_PESQUISA, DS_DESCRICAO) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: tbSatisfResposta
ALTER TABLE dbo.tbSatisfResposta ADD  CONSTRAINT PK_tbSatisfResposta PRIMARY KEY CLUSTERED 
(
	ID_RESPOSTA_SATISF ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX IX_tbSatisfResposta_ID_PESQUISA_SATISF ON dbo.tbSatisfResposta
(
	ID_PESQUISA_SATISF ASC
)
INCLUDE(ID_VISITA) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX IX_tbSatisfResposta_ID_VISITA ON dbo.tbSatisfResposta
(
	ID_VISITA ASC
)
INCLUDE(ID_PESQUISA_SATISF) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: tbSolicitaAtendimento
CREATE NONCLUSTERED INDEX IX_tbSolicitaAtendimento_CD_CLIENTE ON dbo.tbSolicitaAtendimento
(
	CD_CLIENTE ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX IX_tbSolicitaAtendimento_ID_USU_SOLICITANTE ON dbo.tbSolicitaAtendimento
(
	ID_USU_SOLICITANTE ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbSolicitaAtendimento_ID_TIPO_ATENDIMENTO ON dbo.tbSolicitaAtendimento
(
	ID_TIPO_ATENDIMENTO ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX IX_tbSolicitaAtendimento_CD_ATIVO_FIXO ON dbo.tbSolicitaAtendimento
(
	CD_ATIVO_FIXO ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX IX_tbSolicitaAtendimento_ID_STATUS_ATENDIMENTO ON dbo.tbSolicitaAtendimento
(
	ID_STATUS_ATENDIMENTO ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX IX_tbSolicitaAtendimento_ID_OS ON dbo.tbSolicitaAtendimento
(
	ID_OS ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


--TABELA: tbTpEstoqueMovi
CREATE NONCLUSTERED INDEX IX_tbTpEstoqueMovi_ ON dbo.tbTpEstoqueMovi
(
	CD_TP_MOVIMENTACAO ASC
)
INCLUDE(DS_TP_MOVIMENTACAO, DS_NOME_REDUZ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


--TABELA: tbTpEstoqueMovi
CREATE NONCLUSTERED INDEX IX_tbTpEstoqueMovi_CD_TP_MOVIMENTACAO ON dbo.tbTpEstoqueMovi
(
	CD_TP_MOVIMENTACAO ASC
)
INCLUDE(DS_TP_MOVIMENTACAO, DS_NOME_REDUZ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


--TABELA: tbTpMotivoVisitaPadrao
CREATE NONCLUSTERED INDEX IX_tbTpMotivoVisitaPadrao_CD_MOTIVO_VISITA ON dbo.tbTpMotivoVisitaPadrao
(
	CD_MOTIVO_VISITA ASC
)
INCLUDE(DS_MOTIVO_VISITA) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO




--TABELA: tbTpOSPadrao
CREATE NONCLUSTERED INDEX IX_tbTpOSPadrao_CD_TIPO_OS ON dbo.tbTpOSPadrao
(
	CD_TIPO_OS ASC
)
INCLUDE(DS_TIPO_OS) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: tbUsuario
CREATE NONCLUSTERED INDEX IX_tbUsuario_cnmNome ON dbo.tbUsuario
(
	cnmNome ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbUsuario_cd_empresa ON dbo.tbUsuario
(
	cd_empresa ASC
)
INCLUDE(nidUsuario, cnmNome, cdsLogin, bidAtivo) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: tbUsuarioCliente
CREATE NONCLUSTERED INDEX IX_tbUsuarioCliente_nidUsuario ON dbo.tbUsuarioCliente
(
	nidUsuario ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: tbUsuarioPerfil
CREATE NONCLUSTERED INDEX IX_tbUsuarioPerfil_nidUsuario ON dbo.tbUsuarioPerfil
(
	nidUsuario ASC
)
INCLUDE(nidPerfil, bidAtivo) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: tbVisitaPadrao
CREATE NONCLUSTERED INDEX IX_tbVisitaPadrao_DT_DATA_VISITA ON dbo.tbVisitaPadrao
(
	DT_DATA_VISITA ASC
)
INCLUDE(ID_VISITA, ST_STATUS_VISITA, CD_CLIENTE, CD_TECNICO, HR_INICIO, HR_FIM, CD_MOTIVO_VISITA) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbVisitaPadrao_ST_STATUS_VISITA ON dbo.tbVisitaPadrao
(
	ST_STATUS_VISITA ASC
)
INCLUDE(ID_VISITA, DT_DATA_VISITA, CD_CLIENTE, CD_TECNICO, HR_INICIO, HR_FIM, CD_MOTIVO_VISITA) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbVisitaPadrao_CD_CLIENTE ON dbo.tbVisitaPadrao
(
	CD_CLIENTE ASC
)
INCLUDE(ID_VISITA, DT_DATA_VISITA, ST_STATUS_VISITA, CD_TECNICO, HR_INICIO, HR_FIM, CD_MOTIVO_VISITA) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbVisitaPadrao_CD_TECNICO ON dbo.tbVisitaPadrao
(
	CD_TECNICO ASC
)
INCLUDE(ID_VISITA, DT_DATA_VISITA, ST_STATUS_VISITA, CD_CLIENTE, HR_INICIO, HR_FIM, CD_MOTIVO_VISITA) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbVisitaPadrao_CD_MOTIVO_VISITA ON dbo.tbVisitaPadrao
(
	CD_MOTIVO_VISITA ASC
)
INCLUDE(ID_VISITA, DT_DATA_VISITA, ST_STATUS_VISITA, CD_CLIENTE, HR_INICIO, HR_FIM, CD_TECNICO) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


--TABELA: tbWfAcessorioPedido
CREATE NONCLUSTERED INDEX IX_tbWfAcessorioPedido_ID_WF_PEDIDO_EQUIP ON dbo.tbWfAcessorioPedido
(
	ID_WF_PEDIDO_EQUIP ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbWfAcessorioPedido_CD_MODELO ON dbo.tbWfAcessorioPedido
(
	CD_MODELO ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: tbWfGrupoUsu
CREATE NONCLUSTERED INDEX IX_tbWfGrupoUsu_ID_USUARIO ON dbo.tbWfGrupoUsu
(
	ID_USUARIO ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX IX_tbWfGrupoUsu_ID_GRUPOWF ON dbo.tbWfGrupoUsu
(
	ID_GRUPOWF ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


--TABELA: tbWfGrupoXStatusPedidoEquip
CREATE NONCLUSTERED INDEX IX_tbWfGrupoXStatusPedidoEquip_ID_GRUPOWF ON dbo.tbWfGrupoXStatusPedidoEquip
(
	ID_GRUPOWF ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: tbWFGrupoXStatusRR
CREATE NONCLUSTERED INDEX IX_tbWFGrupoXStatusRR_ID_GRUPOWF ON dbo.tbWFGrupoXStatusRR
(
	ID_GRUPOWF ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: tbWfPedidoComent
CREATE NONCLUSTERED INDEX IX_tbWfPedidoComent_ID_WF_PEDIDO_EQUIP ON dbo.tbWfPedidoComent
(
	ID_WF_PEDIDO_EQUIP ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


--TABELA: tbWfPedidoEquip
CREATE NONCLUSTERED INDEX IX_tbWfPedidoEquip_CD_WF_PEDIDO_EQUIP ON dbo.tbWfPedidoEquip
(
	CD_WF_PEDIDO_EQUIP ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbWfPedidoEquip_DT_PEDIDO ON dbo.tbWfPedidoEquip
(
	DT_PEDIDO ASC
)
INCLUDE(CD_WF_PEDIDO_EQUIP) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbWfPedidoEquip_CD_CLIENTE ON dbo.tbWfPedidoEquip
(
	CD_CLIENTE ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbWfPedidoEquip_CD_MODELO ON dbo.tbWfPedidoEquip
(
	CD_MODELO ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbWfPedidoEquip_CD_ATIVO_FIXO_TROCA ON dbo.tbWfPedidoEquip
(
	CD_ATIVO_FIXO_TROCA ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbWfPedidoEquip_ID_USU_EMITENTE ON dbo.tbWfPedidoEquip
(
	ID_USU_EMITENTE ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbWfPedidoEquip_ID_CATEGORIA ON dbo.tbWfPedidoEquip
(
	ID_CATEGORIA ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbWfPedidoEquip_ID_TIPO_SOLICITACAO ON dbo.tbWfPedidoEquip
(
	ID_TIPO_SOLICITACAO ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbWfPedidoEquip_ID_ETIQUETA ON dbo.tbWfPedidoEquip
(
	ID_ETIQUETA ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbWfPedidoEquip_ID_USUARIO_RESPONS ON dbo.tbWfPedidoEquip
(
	ID_USUARIO_RESPONS ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbWfPedidoEquip_CD_GRUPO_RESPONS ON dbo.tbWfPedidoEquip
(
	CD_GRUPO_RESPONS ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbWfPedidoEquip_CD_EMPRESA ON dbo.tbWfPedidoEquip
(
	CD_EMPRESA ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)


--TABELA: tbWfPedidoEquipItem
CREATE NONCLUSTERED INDEX IX_tbWfPedidoEquipItem_CD_ATIVO_FIXO ON dbo.tbWfPedidoEquipItem
(
	CD_ATIVO_FIXO ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbWfPedidoEquipItem_ID_WF_PEDIDO_EQUIPO ON dbo.tbWfPedidoEquipItem
(
	ID_WF_PEDIDO_EQUIP ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: tbWfPedidoEquipLog
CREATE NONCLUSTERED INDEX IX_tbWfPedidoEquipLog_ID_WF_PEDIDO_EQUIP ON dbo.tbWfPedidoEquipLog
(
	ID_WF_PEDIDO_EQUIP ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbWfPedidoEquipLog_ST_STATUS_PEDIDO ON dbo.tbWfPedidoEquipLog
(
	ST_STATUS_PEDIDO ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE NONCLUSTERED INDEX IX_tbWfPedidoEquipLog_ID_USUARIO ON dbo.tbWfPedidoEquipLog
(
	ID_USUARIO ASC
)
INCLUDE(ID_WF_PEDIDO_EQUIP, ST_STATUS_PEDIDO, DT_REGISTRO) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


--TABELA: tbWfTipoSolicitacao
CREATE NONCLUSTERED INDEX IX_tbWfTipoSolicitacao_CD_TIPO_SOLICITACAO ON dbo.tbWfTipoSolicitacao
(
	CD_TIPO_SOLICITACAO ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO



--TABELA: tbWfTipoSolicitacao
CREATE NONCLUSTERED INDEX IX_TST_VENDAS_CLIENTE_CD_CLIENTE ON dbo.TST_VENDAS_CLIENTE
(
	CD_CLIENTE ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX IX_TST_VENDAS_CLIENTE_CD_CONSUMIVEL ON dbo.TST_VENDAS_CLIENTE
(
	CD_CONSUMIVEL ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


CREATE NONCLUSTERED INDEX IX_TST_VENDAS_CLIENTE_CD_MES ON dbo.TST_VENDAS_CLIENTE
(
	CD_MES ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO