GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tbNotificacao](
	[ID_NOTIFICACAO] [bigint] IDENTITY(1,1) NOT NULL,
	[TITULO] [varchar](150) NOT NULL,
	[MENSAGEM] [varchar](max) NOT NULL,
	[LIDA] [bit] NOT NULL,
	[DATA_INCLUSAO] [datetime] NOT NULL,
	[ID_USUARIO] [bigint] NOT NULL,
 CONSTRAINT [PK_tbNotificacao] PRIMARY KEY CLUSTERED 
(
	[ID_NOTIFICACAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[tbNotificacao] ADD  CONSTRAINT [DF_tbNotificacao_LIDA]  DEFAULT ((0)) FOR [LIDA]
GO

ALTER TABLE [dbo].[tbNotificacao]  WITH CHECK ADD  CONSTRAINT [FK_tbNotificacao_tbNotificacao] FOREIGN KEY([ID_USUARIO])
REFERENCES [dbo].[tbUsuario] ([nidUsuario])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[tbNotificacao] CHECK CONSTRAINT [FK_tbNotificacao_tbNotificacao]
GO