GO

/****** Object:  Table [dbo].[TB_PEDIDO_BPCS_NF]    Script Date: 15/07/2022 13:37:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_PEDIDO_BPCS_NF](
	[ID] [numeric](9, 0) IDENTITY(1,1) NOT NULL,
	[ID_ITEM_PEDIDO] [numeric](9, 0) NULL,
	[ID_PEDIDO] [numeric](9, 0) NULL,
	[CD_PECA] [varchar](15) NULL,
	[NR_LINHA][numeric](9,0) NULL,
	[NR_NF][numeric](9,0) NULL,
	[NR_CONTROL][numeric] NULL,
	[DT_FATURAMENTO][DATETIME] NULL,
	[NR_SESM][numeric] (9,0) NULL
 CONSTRAINT [PK_TB_PEDIDO_BPCS_NF] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[TB_PEDIDO_BPCS_NF]  WITH NOCHECK ADD  CONSTRAINT [FK_TB_PEDIDO_BPCS_NF_TB_PEDIDO] FOREIGN KEY([ID_PEDIDO])
REFERENCES [dbo].[TB_PEDIDO] ([ID_PEDIDO])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[TB_PEDIDO_BPCS_NF] CHECK CONSTRAINT [FK_TB_PEDIDO_BPCS_NF_TB_PEDIDO]
GO


